Repository CSID-DGU/2025-1-SCS4031-Gradude-S1, pull requests merged in 2025-06, with the labels that each got.

#74 BE: [fix] 병원 관련 API 에러 해결 #73
  Backend/src/main/java/gradude/springVision/domain/hospital/controller/HospitalController.java
  Backend/src/main/java/gradude/springVision/domain/hospital/dto/response/HospitalDetailResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/hospital/dto/response/HospitalMarkerResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/hospital/dto/response/HospitalSearchResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/hospital/entity/Hospital.java
  Backend/src/main/java/gradude/springVision/domain/hospital/repository/HospitalRepository.java
  Backend/src/main/java/gradude/springVision/domain/hospital/service/HospitalQueryService.java
Labels: 🐛 bug, ✨ feature, BE

#75 FE: [feat] 병원지도 API 연동
  Frontend/App.tsx
  Frontend/src/api/auth.ts
  Frontend/src/api/hospitals.ts
  Frontend/src/components/Calendar.tsx
  Frontend/src/components/hospital/HospitalCard.tsx
  Frontend/src/components/hospital/HospitalDetail.tsx
  Frontend/src/components/hospital/HospitalList.tsx
  Frontend/src/components/hospital/HospitalListCard.tsx
  Frontend/src/constants/navigations.ts
  Frontend/src/hooks/queries/useAuthHelpers.ts
  Frontend/src/hooks/queries/useHospitals.ts
  Frontend/src/hooks/usePermission.ts
  Frontend/src/hooks/useUserLocation.ts
  Frontend/src/navigations/root/RootNavigator.tsx
  Frontend/src/navigations/stack/HomeStackNavigator.tsx
  Frontend/src/navigations/stack/ProfileStackNavigator.tsx
  Frontend/src/navigations/tab/TabNavigator.tsx
  Frontend/src/screens/Health/CalendarScreen.tsx
  Frontend/src/screens/Map/MapScreen.tsx
  Frontend/src/screens/Profile/InfoScreen.tsx
  Frontend/src/screens/Profile/ProfileScreen.tsx
  Frontend/src/screens/auth/KakaoLoginScreen.tsx
  Frontend/src/screens/auth/SignupScreen.tsx
  Frontend/src/store/slices/authSlice.ts
  Frontend/src/types/hospital.ts
  Frontend/src/utils/validate.ts
Labels: ✨ feature, ♻️ refactor, FE

#78 BE: [feat] 건강 수첩 질문 리스트 수정 사항 반영 #69
  Backend/src/main/java/gradude/springVision/domain/diary/dto/request/DiaryRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/diary/dto/response/DiaryResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/diary/entity/Diary.java
  Backend/src/main/java/gradude/springVision/domain/diary/entity/Diet.java
  Backend/src/main/java/gradude/springVision/domain/diary/entity/Drinking.java
  Backend/src/main/java/gradude/springVision/domain/diary/entity/Exercise.java
  Backend/src/main/java/gradude/springVision/domain/diary/entity/Sleep.java
  Backend/src/main/java/gradude/springVision/domain/diary/entity/Smoking.java
  Backend/src/main/java/gradude/springVision/domain/diary/service/DiaryCommandService.java
  Backend/src/main/java/gradude/springVision/global/common/response/ErrorCode.java
Labels: ✨ feature, BE

#82 BE: [fix] CORS 설정에 OPTIONS 메서드 허용 추가 #80
  Backend/src/main/java/gradude/springVision/global/config/CorsConfig.java
Labels: 🐛 bug, BE

#83 BE: [fix] Swagger 서버 URL 설정 추가 #80
  Backend/src/main/java/gradude/springVision/global/config/SwaggerConfig.java
  Backend/src/main/resources/application.yml
Labels: 🐛 bug, BE

#84 BE: [fix] CORS 설정 수정 #80
  Backend/src/main/java/gradude/springVision/global/config/SecurityConfig.java
Labels: 🐛 bug, BE

#86 FE: [feat] 병원지도 마커 수정 및 건강 수첩 API
  Frontend/App.tsx
  Frontend/index.js
  Frontend/ios/Frontend-Bridging-Header.h
  Frontend/ios/Frontend.xcodeproj/project.pbxproj
  Frontend/ios/Frontend/AppDelegate.swift
  Frontend/ios/Frontend/Images.xcassets/AppIcon.appiconset/AppIcon-20@2x.png
  Frontend/ios/Frontend/Images.xcassets/AppIcon.appiconset/AppIcon-20@3x.png
  Frontend/ios/Frontend/Images.xcassets/AppIcon.appiconset/AppIcon-29@2x.png
  Frontend/ios/Frontend/Images.xcassets/AppIcon.appiconset/AppIcon-29@3x.png
  Frontend/ios/Frontend/Images.xcassets/AppIcon.appiconset/AppIcon-40@2x.png
  Frontend/ios/Frontend/Images.xcassets/AppIcon.appiconset/AppIcon-40@3x.png
  Frontend/ios/Frontend/Images.xcassets/AppIcon.appiconset/AppIcon-60@2x~car.png
  Frontend/ios/Frontend/Images.xcassets/AppIcon.appiconset/AppIcon-60@3x~car.png
  Frontend/ios/Frontend/Images.xcassets/AppIcon.appiconset/AppIcon~ios-marketing.png
  Frontend/ios/Frontend/Images.xcassets/AppIcon.appiconset/Contents.json
  Frontend/ios/Frontend/Info.plist
  Frontend/ios/Podfile.lock
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/patches/@react-navigation+stack+7.2.10.patch
  Frontend/src/api/axios.ts
  Frontend/src/api/diagnosis.ts
  Frontend/src/api/healthDiary.ts
  Frontend/src/components/commons/ModalWrapper.tsx
  Frontend/src/components/home/OXButton.tsx
  Frontend/src/components/home/QuestionCard.tsx
  Frontend/src/components/hospital/HospitalCard.tsx
  Frontend/src/components/hospital/HospitalDetail.tsx
  Frontend/src/components/hospital/HospitalListCard.tsx
  Frontend/src/data/healthDiaryQuestions.ts
  Frontend/src/data/hospitals.json
  Frontend/src/data/selfDgsQuestion.ts
  Frontend/src/hooks/queries/useAuth.ts
  Frontend/src/hooks/queries/useHealthDiary.ts
  Frontend/src/navigations/stack/HealthStackNavigator.tsx
  Frontend/src/navigations/stack/HomeStackNavigator.tsx
  Frontend/src/navigations/tab/TabNavigator.tsx
  Frontend/src/screens/Health/CalendarScreen.tsx
  Frontend/src/screens/Health/HealthDairyScreen.tsx
  Frontend/src/screens/Health/HealthResultScreen.tsx
  Frontend/src/screens/Health/HealthScreen.tsx
  Frontend/src/screens/Home/FinalResultScreen.tsx
  Frontend/src/screens/Home/LoadingScreen.tsx
  Frontend/src/screens/Home/MidResultScreen.tsx
  Frontend/src/screens/Home/RecordScreen.tsx
  Frontend/src/screens/Home/SelfDgsScreen.tsx
  Frontend/src/screens/Map/MapScreen.tsx
  Frontend/src/screens/auth/LoginScreen.tsx
  Frontend/src/screens/auth/SignupScreen.tsx
  Frontend/src/store/index.ts
  Frontend/src/store/slices/authSlice.ts
  Frontend/src/types/diagnosis.ts
  Frontend/src/types/healthDiary.ts
  Frontend/src/utils/audioSession.ts
Labels: ✨ feature, ♻️ refactor, FE

#88 BE: [feat] 카카오 로그인 플로우 수정 #87
  Backend/src/main/java/gradude/springVision/domain/user/controller/AuthController.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/request/KakaoLoginRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/response/KakaoUserInfoResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/response/LoginResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/entity/User.java
  Backend/src/main/java/gradude/springVision/domain/user/repository/UserRepository.java
  Backend/src/main/java/gradude/springVision/domain/user/service/AuthCommandService.java
  Backend/src/main/java/gradude/springVision/domain/user/service/OAuthCommandService.java
  Backend/src/main/java/gradude/springVision/global/common/response/ErrorCode.java
Labels: ✨ feature, BE
