Repository CSID-DGU/2025-1-SCS4031-Gradude-S1, pull requests merged in 2025-04, with the labels that each got.

#2 BE: [init] 프로젝트 초기 세팅 #1
  Backend/.gitattributes
  Backend/.gitignore
  Backend/.gitkeep
  Backend/build.gradle
  Backend/gradle/wrapper/gradle-wrapper.jar
  Backend/gradle/wrapper/gradle-wrapper.properties
  Backend/gradlew
  Backend/gradlew.bat
  Backend/settings.gradle
  Backend/src/main/java/gradude/springVision/SpringVisionApplication.java
  Backend/src/main/java/gradude/springVision/global/common/SwaggerConfig.java
  Backend/src/main/java/gradude/springVision/global/common/response/ApiResponse.java
  Backend/src/main/java/gradude/springVision/global/common/response/ErrorCode.java
  Backend/src/main/java/gradude/springVision/global/common/response/ErrorReasonDTO.java
  Backend/src/main/java/gradude/springVision/global/common/response/SuccessCode.java
  Backend/src/main/java/gradude/springVision/global/common/response/SuccessReasonDTO.java
  Backend/src/main/java/gradude/springVision/global/common/response/exception/ExceptionAdvice.java
  Backend/src/main/java/gradude/springVision/global/common/response/exception/GeneralException.java
  Backend/src/main/resources/application.yml
  Backend/src/test/java/gradude/springVision/SpringVisionApplicationTests.java
Labels: ✨ feature, ⚙️ setting, BE

#4 BE: [feat] 회원가입/로그인 구현 #3
  Backend/build.gradle
  Backend/src/main/java/gradude/springVision/SpringVisionApplication.java
  Backend/src/main/java/gradude/springVision/domain/user/controller/AuthController.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/KakaoUserInfoResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/LoginResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/SignupRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/SignupResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/entity/Gender.java
  Backend/src/main/java/gradude/springVision/domain/user/entity/User.java
  Backend/src/main/java/gradude/springVision/domain/user/repository/UserRepository.java
  Backend/src/main/java/gradude/springVision/domain/user/service/AuthCommandService.java
  Backend/src/main/java/gradude/springVision/domain/user/service/OAuthCommandService.java
  Backend/src/main/java/gradude/springVision/global/auth/JwtAuthenticationFilter.java
  Backend/src/main/java/gradude/springVision/global/auth/TokenProvider.java
  Backend/src/main/java/gradude/springVision/global/common/response/ErrorCode.java
  Backend/src/main/java/gradude/springVision/global/config/CorsConfig.java
  Backend/src/main/java/gradude/springVision/global/config/SecurityConfig.java
  Backend/src/main/java/gradude/springVision/global/config/SwaggerConfig.java
  Backend/src/main/java/gradude/springVision/global/util/BaseEntity.java
  Backend/src/main/resources/application.yml
Labels: ✨ feature, BE

#9 BE: [feat] 로그인 추가 구현 #5
  Backend/build.gradle
  Backend/src/main/java/gradude/springVision/domain/user/controller/AuthController.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/KakaoUserInfoResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/LoginResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/SignupRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/TokenRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/TokenResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/entity/User.java
  Backend/src/main/java/gradude/springVision/domain/user/service/AuthCommandService.java
  Backend/src/main/java/gradude/springVision/domain/user/service/OAuthCommandService.java
  Backend/src/main/java/gradude/springVision/global/auth/CustomAuthenticationEntryPoint.java
  Backend/src/main/java/gradude/springVision/global/auth/TokenProvider.java
  Backend/src/main/java/gradude/springVision/global/common/response/exception/ExceptionAdvice.java
  Backend/src/main/java/gradude/springVision/global/common/response/exception/GlobalExceptionHandler.java
  Backend/src/main/java/gradude/springVision/global/config/SecurityConfig.java
  Backend/src/main/resources/application.yml
Labels: ✨ feature, BE

#13 BE: [feat] 건강 수첩 구현 #6
  Backend/src/main/java/gradude/springVision/domain/diary/controller/DiaryController.java
  Backend/src/main/java/gradude/springVision/domain/diary/dto/request/DiaryRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/diary/dto/response/DiaryCalendarResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/diary/dto/response/DiaryDetailResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/diary/dto/response/DiaryGraphResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/diary/dto/response/DiaryResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/diary/entity/Diary.java
  Backend/src/main/java/gradude/springVision/domain/diary/repository/DiaryRepository.java
  Backend/src/main/java/gradude/springVision/domain/diary/service/DiaryCommandService.java
  Backend/src/main/java/gradude/springVision/domain/diary/service/DiaryQueryService.java
  Backend/src/main/java/gradude/springVision/domain/user/controller/AuthController.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/request/SignupRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/request/TokenRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/response/KakaoUserInfoResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/response/LoginResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/response/TokenResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/entity/User.java
  Backend/src/main/java/gradude/springVision/domain/user/service/AuthCommandService.java
  Backend/src/main/java/gradude/springVision/domain/user/service/OAuthCommandService.java
  Backend/src/main/java/gradude/springVision/global/auth/TokenProvider.java
  Backend/src/main/java/gradude/springVision/global/common/response/ErrorCode.java
Labels: ✨ feature, BE

#15 FE: [feat] 카카오 로그인 및 전체 Navigation 구현 #12
  Frontend/.env
  Frontend/.gitignore
  Frontend/.gitkeep
  Frontend/.prettierrc.js
  Frontend/App.tsx
  Frontend/android/app/src/main/java/com/frontend/MainActivity.kt
  Frontend/babel.config.js
  Frontend/index.js
  Frontend/ios/Fonts/Ionicons.ttf
  Frontend/ios/Fonts/MaterialIcons.ttf
  Frontend/ios/Fonts/Octicons.ttf
  Frontend/ios/Frontend.xcodeproj/project.pbxproj
  Frontend/ios/Frontend/Info.plist
  Frontend/ios/Podfile
  Frontend/ios/Podfile.lock
  Frontend/metro.config.js
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/react-native.config.js
  Frontend/src/api/auth.ts
  Frontend/src/api/axios.ts
  Frontend/src/api/queryClient.ts
  Frontend/src/assets/icons/MainIcon.svg
  Frontend/src/assets/icons/MainIconBlue.svg
  Frontend/src/components/commons/CustomButton.tsx
  Frontend/src/constants/colors.ts
  Frontend/src/constants/index.ts
  Frontend/src/constants/keys.ts
  Frontend/src/constants/navigations.ts
  Frontend/src/constants/numbers.ts
  Frontend/src/hooks/queries/useAuth.ts
  Frontend/src/navigations/root/RootNavigator.tsx
  Frontend/src/navigations/stack/AuthStackNavigator.tsx
  Frontend/src/navigations/tap/TapNavigtor.tsx
  Frontend/src/screens/Health/HealthScreen.tsx
  Frontend/src/screens/Home/HomeScreen.tsx
  Frontend/src/screens/Map/MapScreen.tsx
  Frontend/src/screens/Profile/ProfileScreen.tsx
  Frontend/src/screens/auth/KakaoLoginScreen.tsx
  Frontend/src/screens/auth/LoginScreen.tsx
  Frontend/src/screens/auth/SignupScreen.tsx
  Frontend/src/types/auth.ts
  Frontend/src/types/common.ts
  Frontend/src/types/profile.ts
  Frontend/src/types/svg.d.ts
  Frontend/src/utils/encryptStorage.ts
  Frontend/src/utils/header.ts
  Frontend/src/utils/index.ts
  Frontend/tsconfig.json
Labels: ✨ feature, FE
