Repository CSID-DGU/2025-1-SCS4031-Gradude-S1, pull requests merged in 2025-05, with the labels that each got.

#19 FE [feat] 회원가입 화면
  Frontend/App.tsx
  Frontend/ios/Podfile.lock
  Frontend/metro.config.js
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/api/auth.ts
  Frontend/src/assets/icons/ProfileIcon.svg
  Frontend/src/components/GenderToggle.tsx
  Frontend/src/components/commons/CustomButton.tsx
  Frontend/src/components/commons/InputField.tsx
  Frontend/src/constants/colors.ts
  Frontend/src/hooks/queries/useAuth.ts
  Frontend/src/hooks/useForm.ts
  Frontend/src/navigations/root/RootNavigator.tsx
  Frontend/src/navigations/stack/AuthStackNavigator.tsx
  Frontend/src/navigations/tap/TapNavigator.tsx
  Frontend/src/screens/auth/KakaoLoginScreen.tsx
  Frontend/src/screens/auth/LoginScreen.tsx
  Frontend/src/screens/auth/SignupScreen.tsx
  Frontend/src/types/profile.ts
  Frontend/src/utils/common.ts
  Frontend/src/utils/validate.ts
Labels: ✨ feature, FE

#26 BE: [feat] Diagnosis Entity 추가 #8
  Backend/src/main/java/gradude/springVision/domain/diagnosis/entity/Diagnosis.java
Labels: ✨ feature, BE

#27 BE: [fix] DiagnosisRequestDTO 수정 #8
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/request/DiagnosisRequestDTO.java
Labels: 🐛 bug, BE

#28 BE: [feat] Hospital Entity 생성 #24
  Backend/src/main/java/gradude/springVision/domain/hospital/dto/OpeningHour.java
  Backend/src/main/java/gradude/springVision/domain/hospital/entity/Hospital.java
Labels: ✨ feature, BE

#34 FE: [feat] Map Screen 연동
  Frontend/.gitignore
  Frontend/ios/Config.xcconfig
  Frontend/ios/Frontend-Bridging-Header.h
  Frontend/ios/Frontend.xcodeproj/project.pbxproj
  Frontend/ios/Frontend.xcodeproj/xcshareddata/xcschemes/Frontend.xcscheme
  Frontend/ios/Frontend/AppDelegate.swift
  Frontend/ios/Frontend/Info.plist
  Frontend/ios/Podfile
  Frontend/ios/Podfile.lock
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/CustomVideoPlayer.tsx
  Frontend/src/components/commons/ModalWrapper.tsx
  Frontend/src/components/hospital/HospitalCard.tsx
  Frontend/src/components/hospital/HospitalDetail.tsx
  Frontend/src/components/hospital/HospitalList.tsx
  Frontend/src/constants/colors.ts
  Frontend/src/constants/navigations.ts
  Frontend/src/data/hospitals.json
  Frontend/src/hooks/useUserLocation.ts
  Frontend/src/navigations/stack/MapStackNavigator.tsx
  Frontend/src/screens/Home/FinalResultScreen.tsx
  Frontend/src/screens/Map/MapScreen.tsx
  Frontend/src/types/hospital.ts
Labels: ✨ feature, FE

#36 FE: [feat] 건강 수첩 메인 레이아웃
  Frontend/ios/Frontend.xcodeproj/project.pbxproj
  Frontend/ios/Podfile.lock
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/hospital/HospitalCard.tsx
  Frontend/src/constants/navigations.ts
  Frontend/src/navigations/stack/HealthStackNavigator.tsx
  Frontend/src/navigations/stack/HomeStackNavigator.tsx
  Frontend/src/navigations/stack/MapStackNavigator.tsx
  Frontend/src/navigations/tab/TabNavigator.tsx
  Frontend/src/screens/Health/CalendarScreen.tsx
  Frontend/src/screens/Health/FinalResultListScreen.tsx
  Frontend/src/screens/Health/HealthDairyScreen.tsx
  Frontend/src/screens/Health/HealthResultScreen.tsx
  Frontend/src/screens/Health/HealthScreen.tsx
  Frontend/src/screens/Health/StrokeScreen.tsx
  Frontend/src/screens/Home/HomeScreen.tsx
  Frontend/src/screens/Map/MapScreen.tsx
Labels: ✨ feature, FE

#43 BE: [feat] 안면 자가진단 구현 #38
  Backend/src/main/java/gradude/springVision/domain/diagnosis/controller/DiagnosisController.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/request/DiagnosisRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/response/AiDiagnosisResposneDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/response/FaceDiagnosisResposneDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/entity/Diagnosis.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/service/DiagnosisCommandService.java
  Backend/src/main/java/gradude/springVision/domain/hospital/dto/HospitalMapResponseDTO.java
  Backend/src/main/java/gradude/springVision/global/common/response/ErrorCode.java
  Backend/src/main/resources/application.yml
Labels: ✨ feature, BE

#45 BE: [feat] 설문 자가진단 구현 #38
  Backend/src/main/java/gradude/springVision/domain/diagnosis/controller/DiagnosisController.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/request/SelfDiagnosisRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/response/DiagnosisResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/entity/Diagnosis.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/repository/DiagnosisRepository.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/service/DiagnosisCommandService.java
  Backend/src/main/java/gradude/springVision/global/common/response/ErrorCode.java
Labels: ✨ feature, BE

#58 FE: [feat] 녹음 기능 추가 구현
  Frontend/ios/Frontend/AppDelegate.swift
  Frontend/ios/Frontend/Info.plist
  Frontend/ios/Podfile.lock
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/patches/react-native-sound+0.11.2.patch
  Frontend/src/assets/Home/CloseEyeEmoji.svg
  Frontend/src/assets/Home/SmileEmoji.svg
  Frontend/src/assets/Home/StraightEmoji.svg
  Frontend/src/assets/Home/WinkEmoji.svg
  Frontend/src/navigations/stack/HomeStackNavigator.tsx
  Frontend/src/screens/Health/StrokeScreen.tsx
  Frontend/src/screens/Home/FaceSmileScreen.tsx
  Frontend/src/screens/Home/HomeScreen.tsx
  Frontend/src/screens/Home/RecordScreen.tsx
Labels: ✨ feature, FE

#60 BE: [feat] 병원 지도 및 가까운 병원 거리순 조회 #39
  Backend/.gitignore
  Backend/src/main/java/gradude/springVision/domain/hospital/controller/HospitalController.java
  Backend/src/main/java/gradude/springVision/domain/hospital/dto/HospitalDetailResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/hospital/dto/HospitalMarkerResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/hospital/dto/HospitalSearchResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/hospital/entity/Hospital.java
  Backend/src/main/java/gradude/springVision/domain/hospital/repository/HospitalRepository.java
  Backend/src/main/java/gradude/springVision/domain/hospital/service/HospitalQueryService.java
  Backend/src/main/java/gradude/springVision/domain/user/dto/request/SignupRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/user/entity/User.java
Labels: ✨ feature, BE

#61 Be/feat/#39
  Backend/.gitignore
  Backend/src/main/java/gradude/springVision/domain/hospital/controller/HospitalController.java
  Backend/src/main/java/gradude/springVision/domain/hospital/dto/HospitalDetailResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/hospital/entity/OpeningHour.java
  Backend/src/main/java/gradude/springVision/domain/hospital/repository/HospitalRepository.java
Labels: ✨ feature, BE

#64 BE: [feat] 안면, 음성 자가진단 메서드 통합 #55
  Backend/build.gradle
  Backend/src/main/java/gradude/springVision/domain/diagnosis/controller/DiagnosisController.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/controller/FinalDiagnosisController.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/request/FinalDiagnosisRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/response/AiDiagnosisResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/response/AiDiagnosisResposneDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/response/FinalDiagnosisResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/service/DiagnosisCommandService.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/service/FinalDiagnosisService.java
  Backend/src/main/java/gradude/springVision/global/common/response/ErrorCode.java
  Backend/src/main/java/gradude/springVision/global/config/OpenAIConfig.java
  Backend/src/main/resources/application.yml
Labels: ✨ feature, BE

#67 BE: [feat] 자가진단 질문 리스트 수정 사항 반영 #55
  Backend/src/main/java/gradude/springVision/domain/diagnosis/controller/DiagnosisController.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/request/SelfDiagnosisRequestDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/dto/response/DiagnosisResponseDTO.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/entity/Diagnosis.java
  Backend/src/main/java/gradude/springVision/domain/diagnosis/service/DiagnosisCommandService.java
Labels: ✨ feature, BE

#68 FE: [feat] 카카오 로그인 및 회원가입 API 연동
  Frontend/App.tsx
  Frontend/ios/Config.xcconfig
  Frontend/ios/Frontend/Info.plist
  Frontend/ios/Podfile.lock
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/api/auth.ts
  Frontend/src/api/axios.ts
  Frontend/src/hooks/queries/useAuth.ts
  Frontend/src/hooks/queries/useAuthHelpers.ts
  Frontend/src/hooks/useForm.ts
  Frontend/src/navigations/root/RootNavigator.tsx
  Frontend/src/screens/auth/KakaoLoginScreen.tsx
  Frontend/src/screens/auth/LoginScreen.tsx
  Frontend/src/screens/auth/SignupScreen.tsx
  Frontend/src/store/index.ts
  Frontend/src/store/slices/authSlice.ts
  Frontend/src/types/auth.ts
  Frontend/src/types/profile.ts
  Frontend/src/utils/validate.ts
Labels: ✨ feature, ♻️ refactor, FE

#72 BE: [refactor] nickname으로 필드명 통일 #71
  Backend/src/main/java/gradude/springVision/domain/user/dto/response/UserResponseDTO.java
Labels: ♻️ refactor, BE
